### PR TITLE
Create A Readme ( SpaceInvaders - Python ) #43

### PR DESCRIPTION
**Pull request by RupaakSrinivas**
Issue #43 

Adding README.md file for the Spaceinvaders game.
- edit/README

@SubstantialCattle5

### CODE REVIEW

**Comment by SubstantialCattle5** [comment]
When making a pr explain about what you're working on. 
ex - feat/Awesomestuff 
And tag moderators.

**Comment by 3xpl0itk1t** [comment]
Try making your own README template so that you actually learn about mark down :)

> Issue #43
> 
> Adding README.md file for the Spaceinvaders game.
> 
> * edit/README
> 
> @SubstantialCattle5

Try making your own README template so that you actually learn about mark down :)

**Comment by RupaakSrinivas** [comment]
@SubstantialCattle5  updated the README.md file

**Comment by 3xpl0itk1t** [comment]
This resolves the issue #43

**Pull request merged**
