### PR TITLE
Adding a Basic Python Game

### PR DESCRIPTION
**Pull request by realwanheda**

### CODE REVIEW

**Comment by SubstantialCattle5** [comment]
Please tag the issue you're solving as well as the moderators.

**Comment by SubstantialCattle5** [comment]
Also provide a description

**Comment by realwanheda** [comment]
> Please tag the issue you're solving as well as the moderators.

I just wanted to contribute an very basic python game of guess the number i created can you guide me what to do ?

**Comment by SubstantialCattle5** [comment]
You can tag moderators using - @realwanheda

**Comment by realwanheda** [comment]
@@SubstantialCattle5 I have just contributed a code and created a PR

**Pull request merged**
